Make Sumcheck Relations uniform + Efficient Pow
AztecProtocol/barretenberg pull request #119
Opened 2023-02-02 14:42 UTC by adr1anh

# Description

Please provide a paragraph or two giving a summary of the change, including relevant motivation and context.

# Checklist:

- [ ] I have reviewed my diff in github, line by line.
- [ ] Every change is related to the PR description.
- [ ] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this pull request to the issue(s) that it resolves.
- [ ] There are no unexpected formatting changes, superfluous debug logs, or commented-out code.
- [ ] There are no circuit changes, OR specifications in `/markdown/specs` have been updated.
- [ ] There are no circuit changes, OR a cryptographer has been assigned for review.
- [ ] I've updated any terraform that needs updating (e.g. environment variables) for deployment.
- [ ] The branch has been rebased against the head of its merge target.
- [ ] I'm happy for the PR to be merged at the reviewer's next convenience.
- [ ] New functions, classes, etc. have been documented according to the doxygen comment format. Classes and structs must have `@brief` describing the intended functionality.
- [ ] If existing code has been modified, such documentation has been added or updated.

2023-02-07 14:21 UTC, codygunton requested changes

2023-02-07 14:21 UTC, codygunton commented on cpp/src/aztec/honk/pcs/ipa/ipa.test.cpp
> +    constexpr size_t n = 256;
Agree these were running too long.

2023-02-07 14:21 UTC, codygunton commented on cpp/src/aztec/honk/sumcheck/polynomials/pow.hpp
> + * - u₀, …, uⱼ₋₁ the challenges sent by the verifier in the first j rounds.
Following your thesis, they're indexed in reverse order, from $d$ to $1$.

2023-02-07 14:21 UTC, codygunton commented on cpp/src/aztec/honk/sumcheck/polynomials/pow.hpp
> + *   This all works when we reverse the order of the rounds.
It's more important that the comments be correct than clean and easy to read.

2023-02-07 14:21 UTC, codygunton commented on cpp/src/aztec/honk/sumcheck/polynomials/pow.hpp
> + *      edge. It can be written a   cⱼ⋅ ( (1−Xⱼ) + ζ 2ʲ ) ⋅ { ζ^{2ʲ⁺¹} }ⁱ, where cⱼ is the `partial_evaluation_constant`
Checking these formulas. $c_j$ looks correct. I believe that `(1−Xⱼ) + ζ 2ʲ` should be $(1-X_j) + X_j \zeta^{2^j}$. The term `{ ζ^{2ʲ⁺¹} }ⁱ` looks correct -- $\prod_{l > j} (1-X_l) + X_l \zeta^{2^l}$ is the MLE of $(\zeta^{2^{j+1}}, \zeta^{2^{j+1}+1}, \zeta^{2^{j+1}+2},...)$. The phrase "evaluated at the $i$-th edge" means to do the binary decomposition of $i$ and plug it into this polynomial, resulting in $\zeta^{2^{j+1}i} = (\zeta^{2^{j+1}})^{i}$.

2023-02-07 14:21 UTC, codygunton commented on cpp/src/aztec/honk/sumcheck/polynomials/pow.hpp
> + * @brief Simulates the pow polynomial for both the prover and the verifier.
It's not clear what "simulate" means. Could you please rewrite this comment to describe the strategy being taken up front (in particular, equivalence to the original protocol), and also to fix typos and to make it agree with the code? Comments should make the code easier to read, but I feel that the notational and conventional switches here, plus the tiny unicode symbols, make the comment pretty hard to read (I know the code and strategy well, but checking what you did here just took me a long time).

2023-02-07 14:21 UTC, codygunton commented on cpp/src/aztec/honk/sumcheck/polynomials/pow.hpp
> + *      Sʲ(Xⱼ) = ( (1−Xⱼ) + ζ 2ʲ )⋅ ∑ᵢ cⱼ⋅{ ζ^{2ʲ⁺¹} }ⁱ⋅ Sʲᵢ(Xⱼ) = ( (1−Xⱼ) + ζ 2ʲ )⋅Tʲ(Xⱼ).
You repeat this `ζ 2ʲ` thing a few times but you seem to compute the right thing in `univariate_eval`.

2023-02-16 22:33 UTC, codygunton approved these changes
Looks good aside from the one extraneous `params` bit that can be removed.

2023-02-16 22:33 UTC, codygunton commented on cpp/src/aztec/honk/composer/standard_honk_composer.test.cpp
> +    sumcheck::RelationParameters<fr> params{
This appears to be unused. Once it's gone, `zeta` can also go.

2023-02-16 22:33 UTC, codygunton commented on cpp/src/aztec/honk/sumcheck/polynomials/pow.hpp
> + * pow(X) = ∏_{0≤l<d} ((1−Xₗ) + Xₗ⋅ζₗ)
This notation does not agree with the notation used in the rest of our sumcheck code. Elsewhere, we index (following the thesis) from $d$ to $1$, i.e., moving from right to left through the variables $(X_1, \ldots , X_d)$ of our MLEs. As we discussed in person, we will leave this conflicting notation in for now, anticipating a future PR where we uniformize notation to count from $0$ to $d-1$. This will mean rewriting some tests that are tied to the earlier notation.

2023-02-16 22:33 UTC, codygunton commented on cpp/src/aztec/honk/sumcheck/polynomials/pow.hpp
> + *   - ζ_{l-1} = ζ_{l}^2,
For $l = d-1, \ldots, 1$

2023-02-16 22:33 UTC, codygunton commented on cpp/src/aztec/honk/sumcheck/polynomials/pow.hpp
> + *                  = ζ_{   l-1   }^{i} ⋅ ( (1−Xₗ) + Xₗ⋅ζₗ ) ⋅ cₗ,
This is just $\zeta_l$, right?

2023-02-16 22:33 UTC, codygunton commented on cpp/src/aztec/honk/sumcheck/polynomials/pow.hpp
> + * In each round l, the prover should compute the univariate polynomial for the relation defined by P'(X)
The unicode sub and super scripts are tiny and l is nearly indistinguishable from 1 in my VS Code font, so I think eventually this should be rewritten for clarity in that regard, but it's fine for now.

2023-02-16 22:33 UTC, codygunton commented on cpp/src/aztec/honk/sumcheck/polynomials/pow.hpp
> + *                  = ζ_{   l-1   }^{i} ⋅ ( (1−Xₗ) + Xₗ⋅ζₗ ) ⋅ cₗ,
Same question below.

2023-02-16 22:33 UTC, codygunton commented on cpp/src/aztec/honk/sumcheck/polynomials/pow.hpp
> + * P'(u)
Weird linebreak here.

2023-02-16 23:15 UTC, adr1anh commented on cpp/src/aztec/honk/composer/standard_honk_composer.test.cpp
> +    sumcheck::RelationParameters<fr> params{
Removed this struct
Also added a comment in relation.hpp to remove alpha zeta.

2023-02-16 23:51 UTC, adr1anh commented on cpp/src/aztec/honk/sumcheck/polynomials/pow.hpp
> + *                  = ζ_{   l-1   }^{i} ⋅ ( (1−Xₗ) + Xₗ⋅ζₗ ) ⋅ cₗ,
Solved

2023-02-17 00:27 UTC, merged