Zw/noir recursion 2
AztecProtocol/barretenberg pull request #414
Opened 2023-05-03 10:29 UTC by zac-williamson

# Description

PR reduces cost of recursive proof composition in UltraPlonk to under 2^18 constraints.

The cost of "maximal" double recursion is 523,506; under the 2^19 threshold. "Maximal" means the circuit verifies 2 UltraPlonk proofs, where both inner proofs are themselves recursive and contain an aggregation object that must be accumulated by the outer circuit.

Additionally, several security flaws have been noticed and fixed.

### Security Fixes

* pedersen_lookup::hash_single . Fixed bug where we were not validating the sum of the decomposed bit slices matched the input scalar.

* stdlib::recursion::verify_proof . When recovering an aggregation object from public inputs, we now apply range constraints to validate the bigfield limbs have the intended size

* stdlib::recursion::verify_proof . When extracting group elements from the proof, we were constructing biggroup elements directly from the raw proof data. These witnesses were not being linked to the group elements being hashed by stdlib::recursion::transcript . This is now fixed.

* stdlib::recursion::transcript . Previously when splitting field elements into 2 slices to better format the hash preimage buffer, we were not validating that the sum of the slices was less than the field modulus (over the integers). This meant the hash preimage was not unique per proof. This is now fixed.

### Changes 

* UltraComposer::decompose_into_default_range does not create extra range tables to handle "leftover" bits if the range table size is large (e.g. a 27-bit range check will not be decomposed into a 14-bit and a 13-bit check. Instead, 2 14-bit checks will be used in combination with an arithmetic gate to prevent overflow).

* pedersen_lookup::merkle_damgard_compress . The "size" parameter of the Merkle-Damgard construction has been moved to the start of the hash block (not the end). This removes one call to `hash_single` in the case where the IV is constant.

* UltraComposer evaluate_non_native_field_multiplication is no longer cached. evaluate_partial_non_native_field_multiplication is cached. Saves ~6,000+ gates

* pedersen_lookup::compress_with_relaxed_range_constraints . New method that does not apply extra range checks when calling `pedersen_lookup::hash_single`. Used when compressing the recursive transcript and the verification key. The extra range checks are required to ensure the decomposed bit slices that represent the input scalars sum to a value that is < the field modulus (over the integers). We know these values are 31 bytes from previous range constraints and therefore this cannot happen.

* pedersen_lookup::hash_single . Reduced constraints required when performing the above mentioned range check

* bigfield::operator- . Fixed bug where we were not using the UltraPlonk code path to save an addition gate. Fixed bug where UltraPlonk code path computed the wrong output.

* biggroup::validate_on_curve uses `mult_madd` to save on 1 field reduction 

* big group::create_group_element_rom_tables / read_group_element_rom_tables now tracks the maximum value of bigfield limbs added into / read from the table (tracking is worst-case. When reading a limb, its maximum value is the max of every limb in the table).

* biggroup::create_group_element_rom_tables will generate size-6 lookup tables if doing so reduces the total number of tables required 

* biggroup::add_sub new method, computes A + B and A - B. Used in biggroup::create_group_element_rom_tables. Prevents a redundant bigfield addition, subtraction and `assert_is_not_equal` call.

* biggroup::quadruple_and_add will perform 2 doublings and add a vector of points into the result. Used in `biggroup_batch_mul` to save 3 field reductions per iteration

* biggroup::multiple_mongtomery_ladder replaces several `montgomery_ladder` implementations (now deleted). Will perform repeated iterations of the Montgomery ladder (A + B + A). Each successive iteration saves on 1 field reduction at the cost of increased additions.

*  biggroup_nafs replaced calls to `field_t::create_range_constraint` with direct calls to the Composer's method. For UltraPlonk this will prevent an unnecessary addition gate being constructed for each bit.

* biggroup_tables : removed unnecessary `reduce()` calls whenever a negated point was written into the table

 * stdlib::recursion::aggregation_state no longer calls `normalize` on the aggregation object, instead calling `reduce` (the top-level verifier can validate the final outputs are in the correct field
 
 * stdlib::recursion::aggregation_state only calls `normalize` on an aggregation object being added into public inputs 
 
 * stdlib::recursion::verification_key::compress now optimally packs inputs into a minimal number of field elements prior to calling `pedersen::compress`. Saves >10,000 constraints (previously we were splitting each group element into 16 68-bit limbs and hashing them as individual field elements)
 
 
 # Checklist:

- [ ] I have reviewed my diff in github, line by line.
- [ ] Every change is related to the PR description.
- [ ] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this pull request to the issue(s) that it resolves.
- [ ] There are no unexpected formatting changes, superfluous debug logs, or commented-out code.
- [ ] There are no circuit changes, OR specifications in `/markdown/specs` have been updated.
- [ ] There are no circuit changes, OR a cryptographer has been assigned for review.
- [ ] I've updated any terraform that needs updating (e.g. environment variables) for deployment.
- [ ] The branch has been rebased against the head of its merge target.
- [ ] I'm happy for the PR to be merged at the reviewer's next convenience.
- [ ] New functions, classes, etc. have been documented according to the doxygen comment format. Classes and structs must have `@brief` describing the intended functionality.
- [ ] If existing code has been modified, such documentation has been added or updated.

2023-05-05 15:54 UTC, suyash67 commented on cpp/src/barretenberg/plonk/proof_system/verification_key/verification_key.cpp
> +    if (proof_system::ComposerType(composer_type) == ComposerType::PLOOKUP) {
Why is `hash_index` removed? I think we had added it so as to not use the default generators (`hash_index = 0`) since we'd end up using overlapping generators for Merkle hashing and VK. Is that okay?

2023-05-05 19:20 UTC, codygunton reviewed
I looked over what's in stdlib/recursion. As discussed elsewhere, I'm not doing a thorough review here. This is is a preliminary PR introducing complex circuit optimizations, and, as such, recursion in Barretenberg should not be put into production anywhere before a deep audit is conducted (note this is _not_ the code that was put into production as part of Aztec Connect).

2023-05-05 19:20 UTC, codygunton commented on cpp/src/barretenberg/stdlib/recursion/verifier/verifier.hpp
> -    std::vector<uint32_t> proof_witness_indices{
This is moved to a member function on the `aggregation_state`.

2023-05-05 19:20 UTC, codygunton commented on cpp/src/barretenberg/stdlib/recursion/aggregation_state/aggregation_state.hpp
> +        P0 = P0.reduce();
Looks like these reductions were missing before :heavy_check_mark:

2023-05-05 19:20 UTC, codygunton commented on cpp/src/barretenberg/stdlib/recursion/verification_key/verification_key.hpp
> +        // we can only use relaxed range checks in pedersen::compress iff bits_per_element < modulus bits
Not verifying whether this condition is sharp in the current review.

2023-05-05 19:20 UTC, codygunton commented on cpp/src/barretenberg/stdlib/recursion/verification_key/verification_key.hpp
> +    std::vector<field_pt> work_element;
It would be helpful to explain what these data members are.

2023-05-05 19:20 UTC, codygunton commented on cpp/src/barretenberg/stdlib/recursion/verification_key/verification_key.hpp
> +    void slice_element(const field_pt& element, const size_t num_bits)
This is a refactor of the lambda function `split` that was defined in `apply_fiat_shamir`. That function used to split into bytes whereas this one splits into bits.

2023-05-05 19:20 UTC, codygunton commented on cpp/src/barretenberg/stdlib/recursion/transcript/transcript.hpp
> +        PedersenPreimageBuilder<Composer, 31 * 8> preimage_buffer(context);
Magic number 31 * 8 = 248? What's the significance of this?

2023-05-05 19:20 UTC, codygunton commented on cpp/src/barretenberg/stdlib/recursion/verification_key/verification_key.hpp
> +            // We do not perform on_curve() circuit checks when constructing the Curve::g1_ct element.
You're saying this hash check would be done in a circuit? Maybe I misunderstand, but it seems like even if the circuit creator (who constructed the `input_key`) was honest, we're still relying on witnesses being constructed in the default way. Anyway, you make it clear in your comment that there's ambiguity around the security model, something that we can address in the audit.

2023-05-05 19:20 UTC, codygunton commented on cpp/src/barretenberg/stdlib/recursion/verification_key/verification_key.hpp
> +        preimage_buffer.add_element_with_existing_range_constraint(composer_type, 8);
I like this `with_existing` interface.

2023-05-05 19:20 UTC, codygunton commented on cpp/src/barretenberg/stdlib/recursion/verifier/verifier.hpp
> -            (-(previous_output.P1)).reduce()); // TODO: use .normalize() instead? (As per defi bridge project)
`reduce` call is now in `add_proof_outputs_as_public_inputs`

2023-05-05 19:20 UTC, codygunton commented on cpp/src/barretenberg/stdlib/recursion/verifier/verifier.hpp
> -        rhs_elements.push_back((-g1_ct(x1, y1)).normalize());
Not immediately clear why this isn't needed, similarly for `opening_result` below.

2023-05-09 16:59 UTC, Rumata888 requested changes
At a glance everything seems ok, except for the soundness issue in range constraint

2023-05-09 16:59 UTC, Rumata888 commented on cpp/src/barretenberg/plonk/composer/ultra_composer.cpp
> +                create_new_range_constraint(diff_idx, sublimb_mask);
You need to range constrain the limb itself,too. Otherwise it is possible to underflow.

2023-05-09 16:59 UTC, Rumata888 commented on cpp/src/barretenberg/proof_system/circuit_constructors/ultra_circuit_constructor.cpp
> + * @brief The following tests FAILED:
Are they still failing?

2023-05-09 16:59 UTC, Rumata888 commented on cpp/src/barretenberg/stdlib/primitives/biggroup/biggroup_impl.hpp
> +            // std::copy(previous_y.mul_left.begin(), previous_y.mul_left.end(), std::back_inserter(lambda1_left));
Do we need these commented out lines?

2023-05-12 11:11 UTC, suyash67 reviewed
Pedersen stuff looks okay to me, just left one comment about hash index.

2023-05-15 09:26 UTC, zac-williamson commented on cpp/src/barretenberg/stdlib/recursion/verification_key/verification_key.hpp
> +            // We do not perform on_curve() circuit checks when constructing the Curve::g1_ct element.
I think it's ok because the Prover does not have the ability to influence the witness. We can assume that some higher-level logic is going to check the correctness of the verification key hash (e.g. it comes from a valid leaf in a Merkle tree). If circuit creator points are on curve and the Prover-supplied witness is not, the vkey hash won't ma

2023-05-15 09:28 UTC, zac-williamson commented on cpp/src/barretenberg/stdlib/recursion/verifier/verifier.hpp
> -        rhs_elements.push_back((-g1_ct(x1, y1)).normalize());
The multiscalar multiplication algorithm can handle unreduced points. Similar to how stdlib methods that use `field_ct` do not need to call `normalize` constantly (...anymore)

2023-05-15 09:41 UTC, zac-williamson commented on cpp/src/barretenberg/plonk/proof_system/verification_key/verification_key.cpp
> +    if (proof_system::ComposerType(composer_type) == ComposerType::PLOOKUP) {
the methods to compress uint8_t vectors did not take in a hash index. Will fix the proper way but adding this support

2023-05-15 11:09 UTC, zac-williamson commented on cpp/src/barretenberg/stdlib/recursion/transcript/transcript.hpp
> +        PedersenPreimageBuilder<Composer, 31 * 8> preimage_buffer(context);
31 bytes = largest number of bytes we can fit into a field element. Will update w. named constant

2023-05-15 11:12 UTC, zac-williamson commented on cpp/src/barretenberg/proof_system/circuit_constructors/ultra_circuit_constructor.cpp
> + * @brief The following tests FAILED:
good catch. No. That was debugging info from when tests were failing. have removed.

2023-05-17 17:46 UTC, Rumata888 approved these changes
The bug is fixed

2023-05-17 17:47 UTC, merged