feat: Make the circuit constructors field agnostic so we can check circuits on grumpkin
AztecProtocol/barretenberg pull request #534
Opened 2023-06-15 11:56 UTC by maramihali

This PR continues the work of getting Honk over Grumpkin by making the circuit constructors and gates field agnostic and ensuring the `StandardCircuitConstructor` is able to verify basic circuits over Grumpkin.

# Checklist:

- [x] I have reviewed my diff in github, line by line.
- [x] Every change is related to the PR description.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this pull request to the issue(s) that it resolves.
- [x] There are no unexpected formatting changes, superfluous debug logs, or commented-out code.
- [x] There are no circuit changes, OR specifications in `/markdown/specs` have been updated.
- [x] There are no circuit changes, OR a cryptographer has been assigned for review.
- [x] I've updated any terraform that needs updating (e.g. environment variables) for deployment.
- [x] The branch has been rebased against the head of its merge target.
- [x] I'm happy for the PR to be merged at the reviewer's next convenience.
- [x] New functions, classes, etc. have been documented according to the doxygen comment format. Classes and structs must have `@brief` describing the intended functionality.
- [x] If existing code has been modified, such documentation has been added or updated.

2023-06-15 22:39 UTC, kevaundray commented on cpp/src/barretenberg/honk/flavor/standard.hpp
> +    using CircuitConstructor = StandardCiruitConstructor;
```suggestion
    using CircuitConstructor = StandardCircuitConstructor;
```

2023-06-20 12:43 UTC, maramihali commented
I reduced scope to only having standard circuits on Grumpkin because ultra circuits require field-agnostic plookup components and I want to prioritise getting Standard Honk on Grumpkin before moving to Ultra (which should be overall similar but would likely require more components in bberg to be templated)

2023-06-21 17:10 UTC, codygunton requested changes
Nice work, thanks. I'm only asking for cleanup and conversations.

2023-06-21 17:10 UTC, codygunton commented on cpp/src/barretenberg/ecc/curves/bn254/bn254.hpp
> +    using Fq12 = barretenberg::fq12;
Could you give this a more generic name like `PairingTargetField` or something like this? That way, if we have end up implementing another pairing-friendly curve with possibly a different pairing extension degree (not 12), we will not have to change aliases. It's also more readable for someone looking at the library for the first time. It might also more future-proof to not refer to the name of the prime in the alias.

2023-06-21 17:10 UTC, codygunton commented on cpp/src/barretenberg/proof_system/arithmetization/gate_data.hpp
> +// TODO: figure out what to do with this...
Unresolved TODO. If you conclude this does not need to be handled now, please make a github issue and update the comment to read `// TODO(#<issue number>): ...`.

2023-06-21 17:10 UTC, codygunton commented on cpp/src/barretenberg/proof_system/arithmetization/gate_data.hpp
> +// TODO: and this..
Ditto

2023-06-21 17:10 UTC, codygunton commented on cpp/src/barretenberg/proof_system/arithmetization/gate_data.hpp
> +using add_triple = add_triple_<barretenberg::fr>;
Doing this aliaising is ok for now, but probably we'll want an alternative method later so that we don't have `add_triple_grumpkin` etc. Can discuss more when appropriate. Is this just a convenience to avoid having to add an explicit template parameter elsewhere?

2023-06-21 17:10 UTC, codygunton commented on cpp/src/barretenberg/proof_system/arithmetization/gate_data.hpp
> +using add_triple = add_triple_<barretenberg::fr>;
FYI we can probably avoid a lot of boilerplate by turning lines like
`ctx->create_foo_gate(foo_triple{x,...,y,...})`
into lines like
`ctx->create_foo_gate({x,...,y,...})`
IMO explicitly initializing the input struct doesn't add clarity, whereas I do think using the explicit syntax
`ctx->create_foo_gate({.w_1=x,...,.q_m=y,...})`
does help (but I'm not asking for that!).

2023-06-21 17:10 UTC, codygunton commented on cpp/src/barretenberg/proof_system/circuit_constructors/turbo_circuit_constructor.test.cpp
> +    fr accumulator_ofrset = (fr::one() + fr::one()).pow(static_cast<uint64_t>(initial_exponent)).invert();
Find and replate pollution: `ofrset` ~> `offset` in this file

2023-06-21 17:10 UTC, codygunton commented on cpp/src/barretenberg/proof_system/circuit_constructors/ultra_circuit_constructor.test.cpp
> +    fr input_value = fr::random_element();
Doesn't this make the file a little less clear? We'll want to find and replace `barretenberg::fr` to `bn254::fr` at some point in the future, and so I'd rather leave this as it was.

2023-06-21 17:10 UTC, codygunton commented on cpp/src/barretenberg/proof_system/circuit_constructors/ultra_circuit_constructor.cpp
> +     * In this case, we have composer.this->num_gates = n_computation before we execute the following two functions.
Find-and-replace polluting comments.

2023-06-21 17:10 UTC, codygunton commented on cpp/src/barretenberg/proof_system/circuit_constructors/ultra_circuit_constructor.cpp
> +    // We want the this->4th wire this->to represent this->the quotient:
Ditto here and elsewhere in this file.

2023-06-22 17:02 UTC, maramihali commented on cpp/src/barretenberg/ecc/curves/bn254/bn254.hpp
> +    using Fq12 = barretenberg::fq12;
Dyt `TargetField` is enough? You won't have a target field unless the curve supports pairings.

2023-06-22 17:07 UTC, maramihali commented on cpp/src/barretenberg/proof_system/circuit_constructors/ultra_circuit_constructor.test.cpp
> +    fr input_value = fr::random_element();
Makes sense, this change was trigger by the fact that there's fr almost everywhere and then four places with barretenberg::fr and we are `using` the namespace. Should I change all places to `barretenberg::fr `?

2023-06-22 17:08 UTC, maramihali commented on cpp/src/barretenberg/proof_system/circuit_constructors/ultra_circuit_constructor.cpp
> +     * In this case, we have composer.this->num_gates = n_computation before we execute the following two functions.
wops vscode did something funny here, thanks for spotting

2023-06-23 10:58 UTC, maramihali commented on cpp/src/barretenberg/proof_system/arithmetization/gate_data.hpp
> +// TODO: figure out what to do with this...
I cleaned some boilerplatecode as you suggested, thanks for that - my idea is that this is sort of okay to get to MVP with Grumpkin on StandardHonk without much hassle in the rest of the codebase but then should be cleaned up (opened issue , including the read part); the nicest thing to do imo is not have an alias and just make the type for each gates explicit when we refer to them in the codebase. They don't appear in that many places

2023-06-23 10:59 UTC, maramihali commented on cpp/src/barretenberg/proof_system/arithmetization/gate_data.hpp
> +using add_triple = add_triple_<barretenberg::fr>;
I cleaned some boilerplatecode as you suggested, thanks for that - my idea is that this is sort of okay to get to MVP with Grumpkin on StandardHonk without much hassle in the rest of the codebase but then should be cleaned up (opened issue , including the read part); the nicest thing to do imo is not have an alias and just make the type for each gates explicit when we refer to them in the codebase. They don't appear in that many places

2023-06-23 13:53 UTC, maramihali commented
Opens issue #557 for addressing TODOs with templating gates.

2023-07-05 09:00 UTC, codygunton commented on cpp/src/barretenberg/proof_system/arithmetization/gate_data.hpp
> +// TODO: figure out what to do with this...
#557

2023-07-05 09:11 UTC, codygunton approved these changes

2023-07-05 09:11 UTC, merged