chore(ci): Upload build artifacts on releases
AztecProtocol/barretenberg pull request #560
Opened 2023-06-27 22:03 UTC by kevaundray

# Description

This currently uploads the static libraries (WASM, linux, Mac) , the dest folder which contains the transpiled javascript and a barretenberg.wasm file.

What we want long term is:

- No static libraries (instead we have binaries)
- No dest folder, we upload to NPM (this is pending an NPM token and a modification to change the npm version when releases are made)
- Barretenberg.wasm (We still want to keep the barretenberg.wasm binary being upload)

Please provide a paragraph or two giving a summary of the change, including relevant motivation and context.

# Checklist:

- [ ] I have reviewed my diff in github, line by line.
- [ ] Every change is related to the PR description.
- [ ] The branch has been merged with/rebased against the head of its merge target.
- [ ] There are no unexpected formatting changes, superfluous debug logs, or commented-out code.
- [ ] There are no circuit changes, OR a cryptographer has been assigned for review.
- [ ] New functions, classes, etc. have been documented according to the doxygen comment format. Classes and structs must have `@brief` describing the intended functionality.
- [ ] If existing code has been modified, such documentation has been added or updated.
- [ ] No superfluous `include` directives have been added.
- [ ] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to any issue(s) it resolves.
- [ ] I'm happy for the PR to be merged at the reviewer's next convenience.

2023-06-27 22:13 UTC, kevaundray commented
The workflows are dependent, so we do not upload to github unless both MacOS and Linux build. We also don't build unless a release was successfully made. See the `needs` field in the yaml file.

The linux runner builds for both linux and WASM which is why we require WASI for Linux and not for Mac. Since we don't care too much about when the artifacts are uploaded right now, I'm using the free github version, they take about 30-40 minutes to build and publish to GitHub.

A c5ad.16xlarge AWS machine can put this down to 1 minute of build time, but it also costs about $2.7 an hour. Note that we can also take advantage of github caching which would mean that build times may only be bad if you modify code in field arithmetic for example (From conversations, I think its actually not this optimistic)

2023-06-30 08:41 UTC, Rumata888 commented on .github/workflows/release-please.yml
> +    runs-on: ubuntu-large2
Why do we need a large ubuntu machine for downloading and uploading artifacts?

2023-07-04 08:20 UTC, kevaundray commented on .github/workflows/release-please.yml
> +    runs-on: ubuntu-large2
```suggestion
    runs-on: ubuntu-latest
```

2023-07-05 15:25 UTC, charlielye requested changes, later dismissed
It seems there's a lot we need to change here so maybe easier to discuss in person.

2023-07-05 15:25 UTC, charlielye commented on .github/workflows/release-please.yml
> +    runs-on: ubuntu-latest
Can we build on ubuntu 20 LTS (focal) to ensure compatability with mainframe.

2023-07-05 15:25 UTC, charlielye commented on .github/workflows/release-please.yml
> +      - name: Install Bleeding edge CMake
Is stock cmake not sufficient? Do you know what features we use that aren't in stock install?

2023-07-05 15:25 UTC, charlielye commented on .github/workflows/release-please.yml
> +      - name: Install Clang/Ninja/Binaryen
We don't need binaryen anymore.
Was this copied from previous nix stuff as i see nix related files above as well?

2023-07-05 15:25 UTC, charlielye commented on .github/workflows/release-please.yml
> +        run: tar -cvf dest.tar ts/dest
These should be tgz's no?

2023-07-05 15:25 UTC, charlielye commented on .github/workflows/release-please.yml
> +        run: tar -cvf ubuntu-static-lib.tar cpp/build/lib
How come outputting static libs? Were we not going to output the artefects discussed in the thread?

2023-07-05 15:25 UTC, charlielye commented on .github/workflows/release-please.yml
> +          brew install cmake llvm ninja libomp clang-format
omp not needed. we're meant to be using stock llvm now.

2023-07-10 15:35 UTC, kevaundray commented on .github/workflows/release-please.yml
> +          brew install cmake llvm ninja libomp clang-format
```suggestion
          brew install cmake llvm ninja clang-format
```

2023-07-10 16:07 UTC, kevaundray commented on .github/workflows/release-please.yml
> +          sudo apt-get -y install clang clang-format ninja-build binaryen
```suggestion
          sudo apt-get -y install clang clang-format ninja-build
```

2023-07-10 16:08 UTC, kevaundray commented on .github/workflows/release-please.yml
> +      - name: Install Clang/Ninja/Binaryen
```suggestion
      - name: Install Clang/Ninja
```

2023-07-10 16:29 UTC, kevaundray commented on .github/workflows/release-please.yml
> +          cmake --build --preset default ${@/#/--target }
```suggestion
          cmake --build --preset default --target bb
```

2023-07-10 16:30 UTC, kevaundray commented on .github/workflows/release-please.yml
> +          cmake --build --preset default ${@/#/--target }
```suggestion
          cmake --build --preset default -- target bb
```

2023-07-10 16:30 UTC, kevaundray commented on .github/workflows/release-please.yml
> +          cmake --preset default -DCMAKE_BUILD_TYPE=RelWithAssert -DOMP_MULTITHREADING=OFF
```suggestion
          cmake --preset default -DCMAKE_BUILD_TYPE=RelWithAssert
```

2023-07-10 16:30 UTC, kevaundray commented on .github/workflows/release-please.yml
> +          brew install cmake llvm ninja clang-format
```suggestion
          brew install cmake ninja
```

2023-07-10 16:34 UTC, kevaundray commented
token name: `NPM_TOKEN`

2023-07-11 02:33 UTC, kevaundray commented on .github/workflows/release-please.yml
> +    name: Build on Mac
Blocking: Mac builds are currently not compiling

2023-07-11 12:07 UTC, kevaundray commented on .github/workflows/release-please.yml
> +          echo "BREW_PREFIX=$(brew --prefix)" >> $GITHUB_ENV
```suggestion
```

2023-07-11 12:08 UTC, kevaundray commented on .github/workflows/release-please.yml
> +    name: Build on Mac
This is now fixed by using macos-13 ventura and upgrading clang to 14.0.3 (xcode 14.3.1)

2023-07-11 19:34 UTC, merged